---
map:
  ? - lassen
  : ~: 1
  ? - Ihren
  : Designern: 1
  ? - Wohlgemerkt
  : Eine: 1
  ? - nun
  : nicht: 1
    schon: 1
  ? - dem
  : Webseiten: 1
  ? - Handy
  : geeignet: 1
  ? - wird
  : es: 1
  ? - Ihr
  : Budget: 1
  ? - arbeiten
  : Sie: 1
  ? - fertig
  : der: 1
  ? - nämlich
  : ~: 1
  ? - Ihrem
  : Entwickler: 1
  ? - XML
  : Worte: 1
  ? - alte
  : Leier: 1
  ? - Fordern
  : Sie: 1
  ? - müssen
  : wir: 1
  ? - Ende
  : gelesen: 1
  ? - erfüllt
  : ~: 1
  ? - Layout
  : nun: 1
    ist: 1
  ? - wenn
  : sich: 1
    Sie: 1
  ? - das
  : es: 1
    Regelwerk: 1
    Layout: 1
  ? - begleiten
  : möchte: 1
  ? - ""
  : Genau: 1
    Wohlgemerkt: 1
    So: 1
    Was: 1
    Im: 1
    Natürlich: 1
    Meine: 1
    Das: 2
    Denn: 1
    Sehen: 1
    Ich: 2
    Damit: 1
    Diese: 1
    Und: 3
    Es: 1
    Ebenso: 1
    Standards: 1
    Ihr: 1
  ? - werden
  : ~: 1
    Webstandards: 1
  ? - Standards
  : sorgen: 1
    tun?: 1
    halten: 1
    sparen: 1
  ? - Beteiligten
  : aus: 1
  ? - mehr
  : zwei: 1
  ? - ich
  : diese: 1
    ein: 1
    mich: 1
    Ihnen: 1
  ? - Webseiten
  : später: 1
    ~: 1
    müssen: 1
    aufbauen: 1
    für: 1
  ? - dass
  : sich: 1
    Sie: 1
    alle: 1
  ? - größten
  : Nutzen: 1
  ? - einen
  : anderen: 1
    schönen: 1
  ? - Seite
  : für: 1
    die: 1
  ? - Damit
  : das: 1
  ? - nutzen
  : Ihnen: 1
  ? - einmal
  : von: 1
  ? - Entwickler
  : gehört: 1
  ? - paar
  : Zeilen: 1
    weitere: 1
  ? - sich
  : klein: 1
    Webseiten: 1
    warten: 1
    alle: 1
  ? - verschiedenen
  : Browsern: 1
  ? - Eine
  : Seite: 1
  ? - gibt
  : es: 1
  ? - eine
  : Seite: 1
    Erleichterung: 1
  ? - steht
  : und: 1
  ? - Denn
  : esse: 1
  ? - anderen
  : Browser: 1
  ? - sowohl
  : auf: 1
  ? - Sein
  : ist: 1
  ? - »Lorem
  : Ipsum«: 1
  ? - verschiedene
  : Webseiten: 1
  ? - was
  : können: 1
  ? - auf
  : dem: 1
    sich: 1
    verschiedenen: 1
    einem: 1
    Dauer: 1
    etwas: 1
  ? - Opera
  : Safari: 1
  ? - leichter
  : pflegen: 1
  ? - hinzuweisen
  : das: 1
  ? - verdient
  : wahrgenommen: 1
  ? - haben
  : mich: 1
    ~: 2
  ? - der
  : Blindtext: 1
    geplante: 1
    Text: 1
  ? - Netz
  : funktioniert: 1
  ? - Zeit
  : bei: 1
  ? - Dauer
  : danken: 1
  ? - möchte
  : ich: 2
  ? - mich
  : ein: 1
    bis: 1
    jedes: 1
  ? - Meine
  : Mission: 1
  ? - percipi
  : "-": 1
  ? - von
  : Ihrem: 1
    Ihren: 1
  ? - dann
  : wenn: 1
  ? - können
  : Sie: 1
  ? - es
  : Ihnen: 1
    Regeln: 1
    ebenso: 1
  ? - freue
  : ich: 1
  ? - Mission
  : ist: 1
  ? - Bruders
  : »Lorem: 1
  ? - als
  : Lückenfüller: 1
  ? - sind
  : das: 1
  ? - Sehen
  : Sie: 1
  ? - Was
  : für: 1
  ? - werde
  : hier: 1
  ? - leer
  : vorkommt: 1
  ? - hier
  : noch: 1
  ? - Und
  : arbeiten: 1
    weil: 1
    was: 1
  ? - Regeln
  : für: 1
  ? - Mal
  : wenn: 1
  ? - gut
  : für: 1
  ? - Ausdruck
  : oder: 1
  ? - noch
  : die: 1
    einen: 1
  ? - Gelegenheit
  : nutzen: 1
  ? - den
  : Internet: 2
    Entwicklungskosten: 1
    Ausdruck: 1
    größten: 1
  ? - einfach
  : standardkonforme: 1
  ? - alle
  : an: 1
    Beteiligten: 1
    Formate: 1
  ? - ~
  : Überall: 1
    "": 22
  ? - Programmieren
  : einfach: 1
  ? - dieselbe
  : alte: 1
  ? - Gegensatz
  : zu: 1
  ? - weil
  : Sie: 1
  ? - sorgen
  : dafür: 2
  ? - schon
  : die: 1
    einmal: 1
  ? - standardkonforme
  : Webseiten: 1
  ? - Sie
  : ein: 1
    vielleicht: 1
    Webstandards: 1
    nun: 1
    für: 1
    von: 1
    nicht: 1
    mich: 1
  ? - ein
  : paar: 2
    der: 1
  ? - weitere
  : Sätze: 1
  ? - aber
  : ebenso: 1
  ? - Ebenso
  : möchte: 1
  ? - zu
  : werden: 1
    begleiten: 1
    früheren: 1
    diesem: 1
    dienen: 1
  ? - Tag
  : ~: 1
  ? - ist
  : erfüllt: 1
    ~: 1
    wahrgenommen: 1
    fertig: 1
  ? - Beispiel
  : nicht: 1
  ? - diesem
  : Zwecke: 1
  ? - ziehen
  : ~: 1
  ? - So
  : gibt: 1
  ? - nur
  : dann: 1
    als: 1
  ? - richtig
  : angelegt: 1
  ? - aufbauen
  : ~: 1
  ? - Genau
  : zu: 1
  ? - eintrifft
  : ~: 1
  ? - warten
  : ~: 1
  ? - Handys
  : ~: 1
  ? - etwas
  : hinzuweisen: 1
  ? - Browsern
  : im: 1
  ? - Raume
  : steht: 1
  ? - immer
  : im: 1
  ? - Ihnen
  : dafür: 1
    nicht: 1
    noch: 1
    auf: 1
  ? - Internet
  : Explorer: 2
  ? - sondern
  : auf: 1
  ? - Safari
  : und: 1
  ? - programmieren
  : ~: 1
  ? - schönen
  : Tag: 1
  ? - esse
  : est: 1
  ? - gilt
  : für: 1
  ? - zuviel
  : ~: 1
  ? - Webstandards
  : sind: 1
    nämlich: 1
  ? - angelegt
  : "-": 1
  ? - großen
  : Bruders: 1
  ? - Browser
  : programmieren: 1
    wie: 1
  ? - Budget
  : wird: 1
  ? - Text
  : lässt: 1
    eintrifft: 1
  ? - vorkommt
  : springe: 1
  ? - Ipsum«
  : freue: 1
  ? - Zeilen
  : lesen: 1
  ? - Entwicklungskosten
  : und: 1
  ? - und
  : den: 1
    leer: 1
    sich: 1
    sorgen: 1
    Programmieren: 1
    einen: 1
  ? - Leier
  : ~: 1
  ? - lang
  : zu: 1
  ? - Sätze
  : lang: 1
  ? - est
  : percipi: 1
  ? - diese
  : Gelegenheit: 1
    Standards: 1
  ? - Regelwerk
  : auf: 1
  ? - Worte
  : die: 1
  ? - Es
  : reicht: 1
  ? - später
  : leichter: 1
  ? - an
  : diese: 1
  ? - wie
  : für: 1
    Firefox: 1
  ? - Nutzen
  : ziehen: 1
  ? - Firefox
  : Opera: 1
  ? - gehört
  : haben: 1
  ? - Designern
  : und: 1
  ? - Explorer
  : und: 1
    ebenso: 1
  ? - lesen
  : ~: 1
  ? - wünsche
  : Ihnen: 1
  ? - wahrgenommen
  : werden: 1
    zu: 1
  ? - für
  : die: 1
    Standards: 1
    den: 2
    eine: 1
    alle: 1
    HTML: 1
    Browser: 1
  ? - dafür
  : danken: 1
    dass: 2
  ? - einer
  : Webseite: 1
  ? - Darstellung
  : in: 1
    auf: 1
  ? - CSS
  : JavaScript: 1
  ? - Formate
  : ~: 1
  ? - Erleichterung
  : ~: 1
  ? - zwei
  : verschiedene: 1
  ? - funktioniert
  : aber: 1
  ? - tun?
  : Fordern: 1
  ? - Stellung
  : halten: 1
  ? - im
  : Netz: 1
    Raume: 1
    Schatten: 1
  ? - Natürlich
  : nur: 1
  ? - halten
  : bis: 1
    ~: 1
  ? - Schatten
  : meines: 1
  ? - geeignet
  : ist: 1
  ? - jedes
  : Mal: 1
  ? - sparen
  : Zeit: 1
  ? - in
  : Handys: 1
  ? - danken
  : ~: 1
    dass: 1
  ? - springe
  : ich: 1
  ? - bis
  : der: 1
    zum: 1
  ? - wir
  : zum: 1
  ? - Im
  : Gegensatz: 1
  ? - die
  : "-": 1
    Darstellung: 2
    Sie: 1
    Güte: 1
    Stellung: 1
  ? - aus
  : einer: 1
  ? - Ich
  : wünsche: 1
    werde: 1
  ? - Überall
  : dieselbe: 1
  ? - Zwecke
  : erschaffen: 1
  ? - erschaffen
  : immer: 1
  ? - meines
  : großen: 1
  ? - lässt
  : auf: 1
  ? - reicht
  : eine: 1
  ? - bei
  : den: 1
  ? - auch
  : XML: 1
  ? - Diese
  : Standards: 1
  ? - Das
  : Layout: 1
    gilt: 1
  ? - klein
  : und: 1
  ? - Blindtext
  : ~: 1
  ? - "-"
  : sowohl: 1
    Sein: 1
    richtig: 1
  ? - JavaScript
  : oder: 1
  ? - zum
  : Beispiel: 1
    Ende: 1
  ? - pflegen
  : lassen: 1
  ? - früheren
  : Webseiten: 1
  ? - Güte
  : haben: 1
  ? - vielleicht
  : schon: 1
  ? - Lückenfüller
  : zu: 1
  ? - nackt
  : im: 1
  ? - nicht
  : mehr: 1
    nackt: 1
    nur: 1
    zuviel: 1
  ? - HTML
  : CSS: 1
  ? - ebenso
  : gut: 1
    wie: 1
    verdient: 1
  ? - oder
  : auch: 1
    die: 1
  ? - einem
  : Handy: 1
  ? - gelesen
  : haben: 1
  ? - Webseite
  : den: 1
  ? - geplante
  : Text: 1
  ? - dienen
  : sondern: 1
order: 1